#!/usr/bin/env bash

trap stop_playing INT

function stop_playing() {
  killall play 2>/dev/null
}

trap kill_subprocess TERM

function kill_subprocess() {
  kill $pid
  exit 0
}

while true; do
  fswatch -1 -0 --event Created --event Updated out.wav | xargs -I {} -0 play {} &
  pid=$!
  wait
done
